export interface GoogleReview {
  id: string;
  authorName: string;
  authorAvatar: string;
  rating: number;
  dateText: string;
  reviewText: string;
  verified: boolean;
  googleReviewUrl?: string;
}

export const GOOGLE_REVIEWS: GoogleReview[] = [
  {
    id: "rev-1",
    authorName: "Ahmet Hakan Yılmaz",
    authorAvatar: "",
    rating: 5,
    dateText: "2 hafta önce",
    reviewText: "Sapanca'da konakladığımız en lüks ve en temiz bungalov deneyimiydi. Isıtmalı havuzun sıcaklığı harikaydı, kış gününde havuz keyfi bambaşka. Güler yüzlü hizmet için tüm ekibe teşekkür ederiz.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-2",
    authorName: "Selin & Emre Kaya",
    authorAvatar: "",
    rating: 5,
    dateText: "1 ay önce",
    reviewText: "Evlilik yıldönümümüz için Jakuzili VIP Suite tercih ettik. Şömine başında geçirdiğimiz vakit ve sabah verandamıza gelen zengin serpme kahvaltı unutulmazdı. Mahremiyet %100 sağlanmış.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-3",
    authorName: "Burak Özkan",
    authorAvatar: "",
    rating: 5,
    dateText: "3 hafta önce",
    reviewText: "Görsellerde ne görüyorsanız birebir aynısı hatta daha fazlası. Fiber internet hızı harikaydı, doğa içinde uzaktan çalışmak için harika bir ortam. 360 sanal tura bakarak tutmuştuk, tam beklediğimiz gibi çıktı.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-4",
    authorName: "Zeynep Arslan",
    authorAvatar: "",
    rating: 5,
    dateText: "1 ay önce",
    reviewText: "Ailecek 6 kişi Grand Vista VIP evinde kaldık. Bahçesi çok geniş, çocuklar için güvenli ve havuzu pırıl pırıldı. Sapanca'ya her geldiğimizde tek adresimiz artık burası.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-5",
    authorName: "Mert Deniz",
    authorAvatar: "",
    rating: 5,
    dateText: "2 ay önce",
    reviewText: "Panoramik göl manzaralı dome evde konakladık. Gece yatakta yıldızları izlemek muazzam bir duygu. İlgili ev sahibine ve 7/24 asistan hizmetine çok teşekkürler.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-6",
    authorName: "Elif & Kaan Çelik",
    authorAvatar: "",
    rating: 5,
    dateText: "2 ay önce",
    reviewText: "Evcil hayvanımızla birlikte kabul edildiğimiz için çok mutlu olduk. Pati dostumuz bahçede özgürce koştu. Hem lüks hem hayvan dostu bir tesis bulmak harika.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-7",
    authorName: "Caner & Büşra Yurtsever",
    authorAvatar: "",
    rating: 5,
    dateText: "1 ay önce",
    reviewText: "Havuz sıcaklığı 34 derecedeydi, dondurucu havada sıcak havuza girmek rüya gibiydi. Odaların hijyeni ve kullanılan çarşafların temizliği 5 yıldızlı otel kalitesinde.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-8",
    authorName: "Oğuzhan Polat",
    authorAvatar: "",
    rating: 5,
    dateText: "3 hafta önce",
    reviewText: "Sessizlik ve huzur arayanlar için nokta atışı bir yer. Şehrin gürültüsünden tamamen uzak, doğanın sesleriyle uyanıyorsunuz. Personel inanılmaz ilgili ve saygılıydı.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-9",
    authorName: "Gizem & Serkan Aktaş",
    authorAvatar: "",
    rating: 5,
    dateText: "1 ay önce",
    reviewText: "Barbekü ve şömine alanı mükemmel düşünülmüş. Odada Netflix, hızlı Wi-Fi ve kahve makinesi hazır duruyordu. Konfor adına hiçbir eksik yoktu.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-10",
    authorName: "Deniz Karaca",
    authorAvatar: "",
    rating: 5,
    dateText: "2 hafta önce",
    reviewText: "Hafta sonu kaçamağı için geldik ve hayran kaldık. Bahçe peyzajı ve ışıklandırmalar akşam harika bir görsel şölen sunuyor. Mutlaka tekrar geleceğiz.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-11",
    authorName: "Tolga & Seda Şahin",
    authorAvatar: "",
    rating: 5,
    dateText: "1 ay önce",
    reviewText: "Korumalı özel bahçe konsepti sayesinde son derece rahat ettik. Mahremiyete verilen önem takdire şayan. Emeği geçen herkese teşekkürler.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
  {
    id: "rev-12",
    authorName: "Alperen Demirci",
    authorAvatar: "",
    rating: 5,
    dateText: "2 ay önce",
    reviewText: "Sitedeki rezervasyon hesaplayıcı ile tuttuğumuz fiyatın birebir aynı çıkması da güven verdi. Göründüğünden çok daha kaliteli bir işletme.",
    verified: true,
    googleReviewUrl: "https://maps.google.com",
  },
];
